apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webApp
        image: ./app1
---
apiVersion: v1
kind: Service
metadata:
  name: webApi
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5000
