apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\zxcv0\PycharmProjects\UB_test\app1\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app1
  name: app1
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: app1
status:
  loadBalancer: {}
