apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\zxcv0\PycharmProjects\UB_test\app1\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\zxcv0\PycharmProjects\UB_test\app1\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app1
    spec:
      containers:
        - image: app1
          name: app1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
